#!/bin/bash
# vim: set ft=sh

set -e

OUTPUT="$PWD/bosh-rc"
VERSION="$(cat version/version)"
FINAL_VERSION="$(cat final-version/version)"
FLY_BINARIES=fly-binaries/fly-$VERSION.tgz

pushd concourse/
  echo "$FINAL_VERSION" > src/version/VERSION

  mv $FLY_BINARIES src/fly_binaries/
  # work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
  # into release dir, which is invalid cross-device link
  export HOME=$PWD

  bosh -n create-release --tarball --name concourse --version "$VERSION"
  mv releases/concourse/concourse-*.tgz "$OUTPUT"
popd
